<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CompressionEnabled>false</CompressionEnabled> <!-- Disable compression. E.g. for umbraco backoffice files. These files should be precompressed by node and not let dotnet handle it -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Clean" Version="8.0.1" />
    <PackageReference Include="Umbraco.Cms" Version="18.1.0" />
    <PackageReference Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.3" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.AI.Startup" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Web.StaticAssets" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.OpenAI" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Anthropic" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.MicrosoftFoundry" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Google" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Amazon" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Prompt.Startup" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Prompt.Web.StaticAssets" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Agent.Startup" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Agent.Web.StaticAssets" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Agent.UI" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Agent.Copilot" Version="18.*-*" />
    <PackageReference Include="Umbraco.AI.Automate" Version="18.*-*" />
    <PackageReference Include="Umbraco.Automate.Startup" Version="18.*-*" />
    <PackageReference Include="Umbraco.Automate.Web.StaticAssets" Version="18.*-*" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Razor files are needed for the backoffice to work correctly -->
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Remove RazorCompileOnBuild and RazorCompileOnPublish when not using ModelsMode InMemoryAuto -->
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>

</Project>
